/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-    */
/* ex: set filetype=cpp softtabstop=4 shiftwidth=4 tabstop=4 cindent expandtab: */
/* $Id: displayTaskGlobalTaskManager.h 75 2009-02-24 16:47:20Z adeguet1 $ */

#ifndef _displayTaskGlobalTaskManager_h
#define _displayTaskGlobalTaskManager_h

#include <cisstVector.h>
#include <cisstMultiTask.h>
#include <cisstParameterTypes.h>

#include "displayUIGlobalTaskManager.h"

class displayTaskGlobalTaskManager: public mtsTaskPeriodic {

    CMN_DECLARE_SERVICES(CMN_NO_DYNAMIC_CREATION, CMN_LOG_LOD_RUN_ERROR);
    volatile bool ExitFlag;
    
 protected:
    // user interface generated by FTLK/fluid
    displayUIGlobalTaskManager UI;
    
 public:
    // see sineTask.h documentation
    displayTaskGlobalTaskManager(const std::string & taskName, double period);
    ~displayTaskGlobalTaskManager() {};
    void Configure(const std::string & CMN_UNUSED(filename) = "");
    void Startup(void);
    void Run(void);
    void Cleanup(void) {};
    bool GetExitFlag (void) { return ExitFlag;}
};

CMN_DECLARE_SERVICES_INSTANTIATION(displayTaskGlobalTaskManager);

#endif // _displayTaskGlobalTaskManager_h

/*
  Author(s):  Min Yang Jung
  Created on: 2009-06-03

  (C) Copyright 2009 Johns Hopkins University (JHU), All Rights
  Reserved.

--- begin cisst license - do not edit ---

This software is provided "as is" under an open source license, with
no warranty.  The complete license can be found in license.txt and
http://www.cisst.org/cisst/license.txt.

--- end cisst license ---

*/
